/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;
import java.util.Timer;
import java.util.TimerTask;
import modelos.Tiempo;
/**
 *
 * @author Freddy PC
 */
public class Jgame extends javax.swing.JFrame {

    /**
     * Creates new form Jgame
     */
    public Tiempo tiempo = new Tiempo();
    public int i=0;
    public Jgame() {
        setTitle("Dia Mundial del Agua");
        setSize(400,400);
	setLocationRelativeTo(null);
	setDefaultCloseOperation(EXIT_ON_CLOSE);
	setVisible(true);
        setResizable(false);
        initComponents();
        tiempo.Contar();
        //contador.setText();

    }
    /***Contador**/
    
    /*contador*/
    public  void mejores(){
        DB bd = new DB();
        String[] pregunta = bd.generar_pregunta();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        pregunta_numero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contador = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        pregunta = new javax.swing.JLabel();
        opcion_2 = new javax.swing.JButton();
        opcion_4 = new javax.swing.JButton();
        opcion_1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pregunta_numero.setBackground(new java.awt.Color(29, 102, 158));
        pregunta_numero.setFont(new java.awt.Font("3Dumb", 0, 24)); // NOI18N
        pregunta_numero.setForeground(new java.awt.Color(29, 102, 158));
        pregunta_numero.setText("Pregunta 1");
        getContentPane().add(pregunta_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("3Dumb", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 102, 158));
        jLabel3.setText("Tiempo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        contador.setFont(new java.awt.Font("3Dumb", 0, 24)); // NOI18N
        contador.setForeground(new java.awt.Color(29, 102, 158));
        contador.setText("1:30");
        getContentPane().add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        imagen.setText("jLabel6");
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 150, 60));

        pregunta.setFont(new java.awt.Font("Comic Zine OT", 0, 24)); // NOI18N
        pregunta.setText("jLabel7");
        getContentPane().add(pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 350, 60));

        opcion_2.setBackground(new java.awt.Color(9, 142, 75));
        opcion_2.setFont(new java.awt.Font("Daniel Black", 0, 18)); // NOI18N
        opcion_2.setForeground(new java.awt.Color(255, 255, 255));
        opcion_2.setText("Respuesta 2");
        getContentPane().add(opcion_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 200, 50));

        opcion_4.setBackground(new java.awt.Color(46, 119, 172));
        opcion_4.setFont(new java.awt.Font("Daniel Black", 1, 18)); // NOI18N
        opcion_4.setForeground(new java.awt.Color(255, 255, 255));
        opcion_4.setLabel("Respuesta4");
        getContentPane().add(opcion_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 200, 50));

        opcion_1.setBackground(new java.awt.Color(255, 51, 51));
        opcion_1.setFont(new java.awt.Font("Daniel Black", 0, 18)); // NOI18N
        opcion_1.setForeground(new java.awt.Color(255, 255, 255));
        opcion_1.setText("Respuesta 1");
        getContentPane().add(opcion_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 200, 50));

        jButton4.setBackground(new java.awt.Color(3, 135, 102));
        jButton4.setFont(new java.awt.Font("Daniel Black", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Respuesta 3");
        jButton4.setAlignmentY(0.4F);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Juego/assets/juego.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jgame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel contador;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton opcion_1;
    private javax.swing.JButton opcion_2;
    private javax.swing.JButton opcion_4;
    private javax.swing.JLabel pregunta;
    private javax.swing.JLabel pregunta_numero;
    // End of variables declaration//GEN-END:variables

}
